In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd

In [3]:
#create a list with values
data = [10,20, 30, 40, 50]# declering data

In [4]:
#create a Series with default values
my_series = pd.Series([10,20, 30, 40, 50])#data is just a var u can run without it

In [5]:
print(my_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
my_series.max()

50

In [7]:
my_series.sum()

150

In [8]:
#diclering my own index a,b, etc
Index = ["A", "B", "C", "D", "E"]

In [9]:
updated_series = pd.Series(data, index = Index)
print(updated_series)

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [10]:
updated_series["C"] = 7

print(updated_series)

A    10
B    20
C     7
D    40
E    50
dtype: int64

In [11]:
updated_series["f"] = 22

print(updated_series)# i added c an f

A    10
B    20
C     7
D    40
E    50
f    22
dtype: int64

In [12]:
population = {
    "California" : 395382223,
    "Texas" : 29145505,
    "Florida" : 21538187,
    "New york" : 20201249
    
}

In [13]:
# convert dict into series
pope_series = pd.Series(population)

In [14]:
print(pope_series)

California    395382223
Texas          29145505
Florida        21538187
New york       20201249
dtype: int64

In [15]:
#convert to data frames for csv
pope_series = pd.DataFrame(population, index = Index)

In [17]:
pope_series

   California     Texas   Florida  New york
A   395382223  29145505  21538187  20201249
B   395382223  29145505  21538187  20201249
C   395382223  29145505  21538187  20201249
D   395382223  29145505  21538187  20201249
E   395382223  29145505  21538187  20201249

In [19]:
#TO CSV
pope_series.to_csv("Pope.csv")

In [23]:
data1 = pd.read_csv("Pope.csv")

In [24]:
data1

  Unnamed: 0  California     Texas   Florida  New york
0          A   395382223  29145505  21538187  20201249
1          B   395382223  29145505  21538187  20201249
2          C   395382223  29145505  21538187  20201249
3          D   395382223  29145505  21538187  20201249
4          E   395382223  29145505  21538187  20201249

In [26]:
#TO EXCEL
pope_series.to_excel("Pope.xlsx")
data2 = pd.read_excel("Pope.xlsx")
data2

  Unnamed: 0  California     Texas   Florida  New york
0          A   395382223  29145505  21538187  20201249
1          B   395382223  29145505  21538187  20201249
2          C   395382223  29145505  21538187  20201249
3          D   395382223  29145505  21538187  20201249
4          E   395382223  29145505  21538187  20201249